create or replace package ut_pit_call_stack 
  authid definer
as

  /* generated by utPLSQL for SQL Developer on 2021-11-21 10:27:30 */
  
  --%suite(ut_pit_call_stack)
  --%suitepath(alltests)
  
  --%beforeall
  procedure before_all;
  
  --%beforeeach
  procedure before_each;
  
  --%aftereach
  procedure after_each;
  
  --%afterall
  procedure after_all;
  
  --%context (Method PUSH_STACK)
  
  --%test(... pushes a method on the call stack)
  procedure push_stack;
  
  --%test(... pushes a method on the call stack and sets all parameters)
  procedure push_stack_params;
  
  --%test(... pushes two methods on the call stack)
  procedure push_stack_twice;
  
  --%endcontext
  
  --%context (Method POP_STACK)
  
  --%test(... pops a method from the call stack)
  procedure pop_stack;
  
  --%test(... pops a method from the call stack and sets all parameters including timing information)
  procedure pop_stack_params;
  
  --%test(... pushes two methods on the call stack and pops the latter)
  procedure push_twice_pop_stack;
  
  --%test(... empties the call stack if a fatal error has occurred)
  procedure pop_stack_fatal;
  
  --%endcontext
  
  --%context (Method LONG_OP)
  
  --%test(... writes a new entry into V$SESSION_LONGOPS)
  procedure long_op;
  
  --%test(... update a newly created entry in V$SESSION_LONGOPS)
  procedure long_op_update;
  
  --%test(... sets all parameters passed in in V$SESSION_LONGOPS)
  procedure long_op_params;
  
  --%endcontext

end ut_pit_call_stack;
/
